<?php
require_once __DIR__ . '/includes/auth.php'; require_role('student'); require_once __DIR__ . '/includes/clearance_functions.php';
$student=get_student_by_user($pdo,current_user()); $request=$student?get_latest_clearance_request($pdo,$student['student_id']):null; $progress=$request?get_progress_for_request($pdo,$request['request_id']):[];
function ui_status_class($status){$s=strtolower((string)$status);return $s==='approved'?'status-approved':($s==='rejected'?'status-rejected':'status-pending');}
$page_title='Clearance Tracking'; require_once __DIR__ . '/includes/header.php';
?><section class="dashboard"><div class="dashboard-top"><h1>Clearance Tracking</h1><a href="<?php echo BASE_URL; ?>dashboard.php">Back to dashboard</a></div><div class="dashboard-box">
<?php if(!$request): ?><p>You have not started clearance yet.</p><a class="button" href="<?php echo BASE_URL; ?>student_clearance_request.php">Start Clearance</a><?php else: ?>
<p><strong>Overall status:</strong> <span class="status-badge <?php echo ui_status_class($request['overall_status']); ?>"><?php echo htmlspecialchars($request['overall_status']); ?></span></p><p><strong>Current stage:</strong> <?php echo htmlspecialchars($request['current_department']??'Completed'); ?></p><h2>Workflow progress</h2><ol class="clearance-progress"><?php foreach($progress as $item): $status=$item['status']??'Pending'; $current=(int)$request['current_dept_id']===(int)$item['dept_id']; ?><li class="<?php echo strtolower($status)==='approved'?'is-approved':(strtolower($status)==='rejected'?'is-rejected':''); ?> <?php echo $current?'is-current':''; ?>"><span class="progress-step"><?php echo (int)$item['sequence_no']; ?></span><div><strong><?php echo htmlspecialchars($item['dept_name']); ?></strong><?php if(!empty($item['comments'])): ?><small class="field-hint"><?php echo htmlspecialchars($item['comments']); ?></small><?php endif; ?></div><span class="status-badge <?php echo ui_status_class($status); ?>"><?php echo htmlspecialchars($status); ?></span></li><?php endforeach; ?></ol><?php endif; ?>
</div></section><?php require_once __DIR__ . '/includes/footer.php'; ?>
